name: Build Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        arch: [ "arm", "arm64" ]

    name: Build For Android (libraries and apks)
    runs-on: ubuntu-latest
    steps:
      - name: Setup CCache
        uses: Chocobo1/setup-ccache-action@v1.5.1
        with:
          ccache_options: |
            compression=false
    
      - name: Get Angle
        uses: actions/checkout@v5
        with:
          path: 'angle'
          fetch-depth: 1

      - name: Get & Install depot_tools
        run: |
          git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      - name: Angle dependencies caches
        uses: actions/cache@v4
        with:
          key: angle-deps-${{ matrix.arch }}-${{ hashFiles('angle/DEPS') }}
          restore-keys: angle-deps-${{ matrix.arch }}-${{ hashFiles('angle/DEPS') }}
          path: |
            angle/.cipd
            angle/third_party

      - name: Bootstrap and Sync Angle
        run: |
          cd angle
          vpython3 scripts/bootstrap.py
          gclient sync --no-history -j$(nproc)
          
      - name: Make GN arg
        run: |
          cd angle
          mkdir -p out/Android-${{ matrix.arch }}
          
          echo "target_os = \"android\"
          target_cpu = \"${{ matrix.arch }}\"
          is_component_build = false
          is_debug = false
          angle_assert_always_on = false
          is_clang = true
          proprietary_codecs = true
          dcheck_always_on = false
          is_lsan = false
          is_tsan = false
          angle_with_capture_by_default = false
          use_remoteexec = false
          use_reclient = false
          angle_enable_trace_android_logcat = false
          angle_enable_trace_events = false
          angle_enable_vulkan_gpu_trace_events = false
          angle_enable_cl = false
          angle_enable_cl_passthrough = false
          angle_enable_d3d11_compositor_native_window = false
          angle_use_wayland = false
          angle_use_x11 = false
          angle_enable_renderdoc = false
          angle_enable_commit_id = false
          angle_delegate_workers = true
          enable_java_asserts = false
          build_angle_end2end_tests_library = false
          angle_shared_libvulkan = true
          android_keystore_name = \"chromiumdebugkey\"
          android_keystore_password = \"chromium\"
          android_keystore_path = \"//build/android/chromium-debug.keystore\"
          enable_unused_resource_stripping = true
          exclude_unwind_tables = true
          thin_lto_enable_cache = true
          enable_incremental_d8 = true
          use_autogenerated_modules = true
          enable_proguard_obfuscation = true
          enable_arsc_obfuscation = true
          android_static_analysis = \"off\"
          enable_trace_event_bytecode_rewriting = false
          android_unstripped_runtime_outputs = false
          restricted_traces_outside_of_apk = true
          debuggable_apks = false
          use_fuzztest_wrapper = false
          use_relative_vtables_abi = true
          init_stack_vars = false
          init_stack_vars_zero = false
          target_environment = \"device\"
          msan_check_use_after_dtor = false
          msan_eager_checks = false
          msan_track_origins = 0
          disable_android_lint = true
          disable_libfuzzer = true
          angle_enable_cl_compute_only_pipe = true
          angle_enable_cl_testing = false
          angle_vulkan_display_mode = \"direct\"
          angle_enable_custom_vulkan_cmd_buffers = true
          angle_enable_custom_vulkan_outside_render_pass_cmd_buffers = true
          angle_enable_custom_vulkan_render_pass_cmd_buffers = true
          angle_use_gbm = false
          use_clang_coverage = false
          use_sanitizer_coverage = false
          use_ghash = true
          coverage_instrumentation_input_file = \"\"
          angle_enable_gl_null = false
          angle_build_mesa = false
          angle_enable_unwind_backtrace_support = false
          angle_enable_overlay = false
          angle_enable_perf_counter_output = false
          angle_force_context_check_every_call = false
          angle_debug_layers_enabled = false
          angle_enable_abseil = false
          angle_dump_pipeline_cache_graph = false
          angle_test_enable_system_egl = false
          angle_use_vulkan_null_display = false
          angle_enable_essl = false
          angle_enable_glsl = true
          angle_enable_hlsl = false
          angle_enable_gl = false
          angle_enable_d3d9 = false
          angle_enable_d3d11 = false
          angle_enable_null = false
          angle_enable_metal = false
          angle_enable_wgpu = false
          angle_enable_swiftshader = false
          angle_expose_non_conformant_extensions_and_versions = true
          build_angle_deqp_tests = false
          angle_has_frame_capture = false
          angle_build_tests = false
          angle_enable_vulkan = true
          angle_enable_vulkan_validation_layers = false
          angle_enable_vulkan_system_info = false
          angle_enable_context_mutex_recursion = false
          angle_enable_global_mutex_recursion = false
          angle_enable_global_mutex_load_time_allocate = false
          angle_use_android_tls_slot = true
          angle_always_log_info = false
          angle_enable_platform_trace_events = false
          build_mojo_proxy = false
          is_wexit_time_destructors_default = false
          v8_current_cpu = \"\"
          v8_target_cpu = \"\"
          angle_standalone = true
          symbol_level = 0
          enable_resource_allowlist_generation = false
          strip_debug_info = true
          use_thin_lto = true
          thin_lto_enable_optimizations = true
          angle_build_all = false
          enable_iterator_debugging = false
          is_chrome_branded = false
          enable_full_stack_frames_for_profiling = false
          use_icf = true
          use_sized_deallocation = true
          cc_wrapper = \"env CCACHE_SLOPPINESS=time_macros ccache\"
          use_rtti = false
          is_official_build = true
          is_ubsan = false
          is_asan = false
          optimize_for_size = false
          optimize_for_fuzzing = false
          enable_profiling = false
          use_sysroot = false
          angle_enable_trace = false
          fatal_linker_warnings = false
          use_cfi_icall = false
          use_cfi_diag = false
          use_lld = true
          use_custom_libcxx = true
          chrome_pgo_phase = 0
          angle_has_histograms = false
          angle_has_rapidjson = false
          clang_use_chrome_plugins = false
          clang_unsafe_buffers_paths = \"//unsafe_buffers_paths.txt\"
          use_llvm_libatomic = false
          tests_have_location_tags = false
          vma_vulkan_headers_dir = \"//third_party/vulkan-headers/src\"
          use_siso = true
          use_clang_modules = false
          android_ndk_api_level = 30
          using_mismatched_sample_profile = false
          android_channel = \"canary\"
          libcxx_natvis_include = false
          is_high_end_android = true
          toolchain_allows_use_partition_alloc_as_malloc = true
          use_ml_inliner = false
          enable_expensive_dchecks = false
          angle_enable_gl_desktop_backend = false
          angle_enable_share_context_lock = false
          archive_seed_corpus = true
          arm_arch = \"armv8-a\"
          arm_fpu = \"neon-fp-armv8\"
          arm_optionally_use_neon = true
          arm_tune = \"cortex-a77\"
          arm_use_neon = true
          arm_use_thumb = true
          arm_version = 8
          angle_build_vulkan_system_info = false
          use_dwarf5 = false
          use_debug_fission = false
          enable_new_standalone_webview_settings = false
          enable_baseline_profiles = true
          enable_call_graph_profile_sort = true
          angle_enable_crc_for_pipeline_cache = false
          " > out/Android-${{ matrix.arch }}/args.gn

          gn gen out/Android-${{ matrix.arch }} --threads=$(nproc)
          gn args out/Android-${{ matrix.arch }} --list --short 

      - name: Build Angle (libraries)
        run: |
          cd angle
          autoninja -j$(nproc) -C out/Android-${{ matrix.arch }}

      - name: Build Angle (apk)
        run: |
          cd angle
          autoninja -j$(nproc) -C out/Android-${{ matrix.arch }} angle_apks

      - name: Upload Build Outputs (apk)
        uses: actions/upload-artifact@v4
        with:
          name: apks-${{ matrix.arch }}
          path: | 
            angle/out/Android-${{ matrix.arch }}/apks
          retention-days: 1
          
      - name: Upload Build Outputs (libs)
        uses: actions/upload-artifact@v4
        with:
          name: libs-${{ matrix.arch }}
          path: |
            angle/out/Android-${{ matrix.arch }}/*.so
            angle/out/Android-${{ matrix.arch }}/lib.unstripped
          retention-days: 1
